### ISSUE TITLE
MGI GPAD file is missing 'MGI:' in column 2

### ISSUE THREAD

**Issue by ukemi** [geneontology/minerva#199]
Recently column 2 in the GPAD output has been changed so that identifiers no longer contain the 'MGI:'. Instead, they just have the numerical portion of the identifier.

 https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/mgi.gpad

**Comment by kltm** [comment]
@cmungall @balhoff Has there been any upstream change to explain this?

**Comment by balhoff** [comment]
There has been change in the JSON-LD context files (https://github.com/geneontology/go-site/issues/617). I will need to dig further to see if that is the culprit.

**Comment by ukemi** [comment]
@loricorbani

**Comment by ukemi** [comment]
In Noctua I see the identifiers being of the correct prefix--identifier format. Looking at:
http://noctua.berkeleybop.org/editor/graph/gomodel:5b318d0900000110

The enabled by individual for _Cdc42_ is represented as '[MGI:MGI:106211] Cdc42 mouse' this should parse correctly into MGI in column 1 and MGI:106211 in column 2.

**Comment by pgaudet** [comment]
So this is resolved ?

**Comment by cmungall** [comment]
`curl -L -s https://build.berkeleybop.org/job/export-lego-to-gpad-sparql/lastSuccessfulBuild/artifact/legacy/mgi.gpad | grep MGI`

no, not resolved

**Comment by balhoff** [comment]
This should be resolved now.
